# Generated by Django 5.1.15 on 2026-01-18 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eve_character_id', models.BigIntegerField(db_index=True, help_text='EVE Online Character ID (from SSO)', unique=True)),
                ('eve_character_name', models.CharField(help_text='EVE Online Character Name', max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, max_length=255)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('alliance_name', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth2 refresh token')),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['eve_character_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('skills_data', models.JSONField(blank=True, null=True)),
                ('skills_synced_at', models.DateTimeField(blank=True, null=True)),
                ('skill_queue_data', models.JSONField(blank=True, null=True)),
                ('skill_queue_synced_at', models.DateTimeField(blank=True, null=True)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('wallet_synced_at', models.DateTimeField(blank=True, null=True)),
                ('assets_data', models.JSONField(blank=True, null=True)),
                ('assets_synced_at', models.DateTimeField(blank=True, null=True)),
                ('orders_data', models.JSONField(blank=True, null=True)),
                ('orders_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
    ]
