# Generated by agent-evewire for auth source pluggable architecture

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='auth_source',
            field=models.CharField(
                max_length=50,
                default='esi_sso',
                db_index=True,
                help_text='Authentication source for this character (esi_sso, gice, etc.)'
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='auth_source_data',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text='Additional authentication data from auth source'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='refresh_token',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Encrypted OAuth2/OIDC refresh token (may be None for GICE)'
            ),
        ),
    ]
