# Generated by Django 5.1.15 on 2026-01-18 06:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=10)),
                ('creator_corporation_id', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('date_founded', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'alliance',
                'verbose_name_plural': 'alliances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=10)),
                ('faction_id', models.IntegerField(blank=True, null=True)),
                ('is_npc', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'corporation',
                'verbose_name_plural': 'corporations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('solar_system_id', models.IntegerField(blank=True, null=True)),
                ('corporation_id', models.IntegerField(blank=True, null=True)),
                ('is_unique', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'faction',
                'verbose_name_plural': 'factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('group_id', models.IntegerField(db_index=True, null=True)),
                ('category_id', models.IntegerField(db_index=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('portion_size', models.IntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'item type',
                'verbose_name_plural': 'item types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('constellation_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(db_index=True, null=True)),
                ('security_class', models.CharField(blank=True, max_length=10)),
                ('security', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'solar system',
                'verbose_name_plural': 'solar systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('solar_system_id', models.IntegerField(db_index=True)),
                ('corporation_id', models.IntegerField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('is_conquerable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='assets_data',
        ),
        migrations.RemoveField(
            model_name='character',
            name='assets_synced_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='orders_data',
        ),
        migrations.RemoveField(
            model_name='character',
            name='orders_synced_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_queue_data',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_queue_synced_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skills_data',
        ),
        migrations.AddField(
            model_name='character',
            name='total_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity', models.IntegerField(default=1)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, max_length=20)),
                ('location_flag', models.CharField(blank=True, max_length=50)),
                ('is_singleton', models.BooleanField(default=False)),
                ('is_blueprint_copy', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.character')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.characterasset')),
            ],
            options={
                'verbose_name': 'character asset',
                'verbose_name_plural': 'character assets',
                'ordering': ['character', 'location_id', 'location_flag'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_buy_order', models.BooleanField(default=False)),
                ('type_id', models.IntegerField(db_index=True)),
                ('region_id', models.IntegerField(db_index=True)),
                ('station_id', models.BigIntegerField()),
                ('system_id', models.IntegerField()),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('min_volume', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issued', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('range', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('escrow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to='core.character')),
            ],
            options={
                'verbose_name': 'market order',
                'verbose_name_plural': 'market orders',
                'ordering': ['-issued'],
            },
        ),
        migrations.CreateModel(
            name='WalletJournalEntry',
            fields=[
                ('entry_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('first_party_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ref_type', models.CharField(max_length=50)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_receiver_id', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_journal', to='core.character')),
            ],
            options={
                'verbose_name': 'wallet journal entry',
                'verbose_name_plural': 'wallet journal entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('is_buy', models.BooleanField(default=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('journal_ref_id', models.BigIntegerField(blank=True, null=True)),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('type_id', models.IntegerField(db_index=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='core.character')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.IntegerField(db_index=True)),
                ('skill_level', models.SmallIntegerField(default=0)),
                ('skillpoints_in_skill', models.IntegerField(default=0)),
                ('trained_skill_level', models.SmallIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.character')),
            ],
            options={
                'verbose_name': 'character skill',
                'verbose_name_plural': 'character skills',
                'ordering': ['skill_id'],
                'unique_together': {('character', 'skill_id')},
            },
        ),
        migrations.CreateModel(
            name='SkillQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.IntegerField()),
                ('skill_id', models.IntegerField(db_index=True)),
                ('finish_level', models.SmallIntegerField()),
                ('level_start_sp', models.IntegerField()),
                ('level_end_sp', models.IntegerField()),
                ('training_start_time', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_queue', to='core.character')),
            ],
            options={
                'verbose_name': 'skill queue item',
                'verbose_name_plural': 'skill queue items',
                'ordering': ['character', 'queue_position'],
                'unique_together': {('character', 'queue_position')},
            },
        ),
    ]
