# Generated by Django 5.2.10 on 2026-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_industryjob_nullable_solar_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='needs_reauth',
            field=models.BooleanField(default=False, help_text='User must re-authenticate via SSO to restore sync functionality'),
        ),
    ]
