# Generated by Django 5.2.10 on 2026-01-20 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sde_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeattribute',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='characterattributes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='characterimplant',
            table=None,
        ),
        migrations.CreateModel(
            name='Doctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ship_type_id', models.IntegerField(db_index=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('fit_count', models.IntegerField(blank=True, help_text='Number of fits in this cluster', null=True)),
                ('avg_similarity', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this doctrine is currently in use')),
                ('tags', models.JSONField(blank=True, default=dict, help_text="User-defined tags (e.g., {'role': 'logi', 'tier': '1'})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'doctrine',
                'verbose_name_plural': 'doctrines',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cluster_id__isnull', False)), fields=('ship_type_id', 'cluster_id'), name='unique_cluster_per_ship')],
            },
        ),
        migrations.CreateModel(
            name='AssetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField(db_index=True, help_text='CharacterAsset.item_id')),
                ('is_match', models.BooleanField(default=False, help_text='True if asset matches doctrine')),
                ('match_score', models.FloatField(default=0.0, help_text='Match percentage (0-1)')),
                ('missing_modules', models.JSONField(default=list, help_text='List of missing module type_ids')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_matches', to='core.character')),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_matches', to='core.doctrine')),
            ],
            options={
                'verbose_name': 'asset match',
                'verbose_name_plural': 'asset matches',
                'ordering': ['-match_score', 'doctrine'],
                'indexes': [models.Index(fields=['character', 'is_match', 'match_score'], name='core_assetm_charact_be7a10_idx'), models.Index(fields=['calculated_at'], name='core_assetm_calcula_3e8e6c_idx')],
                'unique_together': {('character', 'doctrine', 'asset_id')},
            },
        ),
        migrations.CreateModel(
            name='DoctrineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('high', 'High Slot'), ('med', 'Medium Slot'), ('low', 'Low Slot'), ('rig', 'Rig Slot'), ('subsystem', 'Subsystem Slot')], max_length=20)),
                ('position', models.IntegerField(help_text='Position within the slot type (0-indexed)')),
                ('module_type_id', models.IntegerField(db_index=True, help_text='ItemType ID for the module')),
                ('usage_count', models.IntegerField(blank=True, help_text='How many fits had this module', null=True)),
                ('usage_percentage', models.FloatField(blank=True, help_text='Percentage of fits with this module', null=True)),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.doctrine')),
            ],
            options={
                'verbose_name': 'doctrine entry',
                'verbose_name_plural': 'doctrine entries',
                'ordering': ['doctrine', 'slot_type', 'position'],
                'unique_together': {('doctrine', 'slot_type', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of ships to fit out')),
                ('location_id', models.BigIntegerField(db_index=True, help_text='Station/structure ID')),
                ('location_type', models.CharField(help_text='station, structure, or solar_system', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Fulfilled'), ('complete', 'Complete'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('items_to_buy', models.JSONField(default=dict, help_text='{type_id: quantity_needed}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.character')),
                ('doctrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='core.doctrine')),
            ],
            options={
                'verbose_name': 'shopping list',
                'verbose_name_plural': 'shopping lists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['character', 'status'], name='core_shoppi_charact_acb1cc_idx'), models.Index(fields=['location_id', 'status'], name='core_shoppi_locatio_6ab1d6_idx')],
            },
        ),
    ]
