# Generated by Django 5.2.10 on 2026-01-21 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sde_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='industry_jobs_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='characterattributes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='characterimplant',
            table=None,
        ),
        migrations.CreateModel(
            name='IndustryJob',
            fields=[
                ('job_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activity_id', models.SmallIntegerField(db_index=True)),
                ('status', models.SmallIntegerField(db_index=True)),
                ('blueprint_id', models.BigIntegerField(db_index=True)),
                ('blueprint_type_id', models.IntegerField(db_index=True)),
                ('blueprint_location_id', models.BigIntegerField(blank=True, null=True)),
                ('product_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('station_id', models.BigIntegerField(db_index=True)),
                ('solar_system_id', models.IntegerField(db_index=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('pause_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completed_character_id', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('attempts', models.SmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_jobs', to='core.character')),
            ],
            options={
                'verbose_name': 'industry job',
                'verbose_name_plural': 'industry jobs',
                'ordering': ['-start_date'],
            },
        ),
    ]
