# Generated by Django 5.2.10 on 2026-02-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_contract_primary_key'),
    ]

    operations = [
        # Add record_id field (the correct ESI field)
        migrations.AddField(
            model_name='contractitem',
            name='record_id',
            field=models.BigIntegerField(db_index=True),
        ),
        # Remove the old unique constraint on contract_id + item_id
        migrations.AlterUniqueTogether(
            name='contractitem',
            unique_together=set(),
        ),
        # Remove item_id field (not in ESI spec - phantom field)
        migrations.RemoveField(
            model_name='contractitem',
            name='item_id',
        ),
        # Add new unique constraint on contract_id + record_id
        migrations.AlterUniqueTogether(
            name='contractitem',
            unique_together={('contract', 'record_id')},
        ),
    ]
