# Generated by Django 5.2.10 on 2026-01-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_character_industry_jobs_synced_at_and_more'),
        ('core', '0008_rename_doctrine_to_fitting'),
    ]

    operations = [
    ]
