# Generated by Django 5.2.10 on 2026-01-21 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260121_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrderHistory',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_buy_order', models.BooleanField(default=False)),
                ('type_id', models.IntegerField(db_index=True)),
                ('region_id', models.IntegerField(db_index=True)),
                ('station_id', models.BigIntegerField()),
                ('system_id', models.IntegerField()),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('min_volume', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('issued', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('range', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('escrow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'market order history',
                'verbose_name_plural': 'market order history',
                'ordering': ['-issued'],
            },
        ),
        migrations.AlterModelOptions(
            name='fitting',
            options={'ordering': ['name'], 'verbose_name': 'fitting', 'verbose_name_plural': 'fittings'},
        ),
        migrations.AlterModelOptions(
            name='fittingentry',
            options={'ordering': ['fitting', 'slot_type', 'position'], 'verbose_name': 'fitting entry', 'verbose_name_plural': 'fitting entries'},
        ),
        migrations.AlterModelOptions(
            name='fittingmatch',
            options={'ordering': ['-match_score', 'fitting'], 'verbose_name': 'fitting match', 'verbose_name_plural': 'fitting matches'},
        ),
        migrations.RenameIndex(
            model_name='fittingmatch',
            new_name='core_fittin_charact_1d917d_idx',
            old_name='core_assetm_charact_be7a10_idx',
        ),
        migrations.RenameIndex(
            model_name='fittingmatch',
            new_name='core_fittin_calcula_3fdf43_idx',
            old_name='core_assetm_calcula_3e8e6c_idx',
        ),
        migrations.AddField(
            model_name='character',
            name='orders_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this fitting is currently in use'),
        ),
        migrations.AlterField(
            model_name='fittingmatch',
            name='is_match',
            field=models.BooleanField(default=False, help_text='True if asset matches fitting'),
        ),
        migrations.AddField(
            model_name='marketorderhistory',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_order_history', to='core.character'),
        ),
    ]
