# Generated by Django 5.2.10 on 2026-01-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_marketorderhistory_alter_fitting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
