# Generated by Django 5.2.10 on 2026-01-21 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_marketorderhistory_alter_fitting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(blank=True, help_text='Specific characters to include in this campaign. Leave empty for all.', related_name='trade_campaigns', to='core.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trade campaign',
                'verbose_name_plural': 'trade campaigns',
                'db_table': 'core_trade_campaign',
                'ordering': ['-start_date'],
            },
        ),
    ]
