# Generated by Django 5.2.10 on 2026-01-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_marketorderhistory_alter_fitting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='contracts_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(db_index=True, max_length=25)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('for_corporation', models.BooleanField(default=False)),
                ('availability', models.CharField(max_length=20)),
                ('date_issued', models.DateTimeField(db_index=True)),
                ('date_expired', models.DateTimeField(db_index=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('issuer_id', models.IntegerField(db_index=True)),
                ('issuer_corporation_id', models.IntegerField()),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('acceptor_id', models.IntegerField(blank=True, null=True)),
                ('days_to_complete', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('collateral', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.character')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(db_index=True)),
                ('type_id', models.IntegerField(db_index=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_included', models.BooleanField(default=True)),
                ('is_singleton', models.BooleanField(default=False)),
                ('raw_quantity', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.contract')),
            ],
            options={
                'verbose_name': 'contract item',
                'verbose_name_plural': 'contract items',
                'ordering': ['contract', 'type_id'],
                'unique_together': {('contract', 'item_id')},
            },
        ),
    ]
