# Generated by Django 5.2.10 on 2026-01-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_character_contracts_synced_at_contract_contractitem'),
        ('core', '0011_core_trade_campaign'),
        ('core', '0011_itemtype_sell_price'),
    ]

    operations = [
    ]
