# Generated by Django 5.2.10 on 2026-01-21 19:52

from django.db import migrations, models
import random
import string


def generate_username():
    """Generate a random username."""
    return f"pilot_{''.join(random.choices(string.ascii_lowercase + string.digits, k=12))}"


def populate_usernames_and_character_fields(apps, schema_editor):
    """
    Populate User.username for existing users and Character fields from User data.
    """
    User = apps.get_model('core', 'User')
    Character = apps.get_model('core', 'Character')

    # For each user, generate a username
    for user in User.objects.all():
        if not user.username:
            username = generate_username()
            # Ensure uniqueness
            while User.objects.filter(username=username).exists():
                username = generate_username()
            user.username = username
            user.save(update_fields=['username'])

    # For each character, populate fields from the related User
    for character in Character.objects.all():
        user = character.user
        if not character.character_name and user.eve_character_name:
            character.character_name = user.eve_character_name
        if not character.corporation_name and user.corporation_name:
            character.corporation_name = user.corporation_name
        if not character.alliance_name and user.alliance_name:
            character.alliance_name = user.alliance_name
        if not character.corporation_id and user.corporation_id:
            character.corporation_id = user.corporation_id
        if not character.alliance_id and user.alliance_id:
            character.alliance_id = user.alliance_id
        # Move refresh_token and token_expires from User to Character
        if not character.refresh_token and user.refresh_token:
            character.refresh_token = user.refresh_token
        if not character.token_expires and user.token_expires:
            character.token_expires = user.token_expires
        character.save(update_fields=[
            'character_name', 'corporation_name', 'alliance_name',
            'corporation_id', 'alliance_id', 'refresh_token', 'token_expires'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260121_1952'),
    ]

    operations = [
        # Step 1: Add new fields to User model (nullable initially)
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, unique=True, db_index=True, help_text='Auto-generated username for authentication'),
            preserve_default=False,
        ),
        # Remove unique constraint from eve_character_id
        migrations.AlterField(
            model_name='user',
            name='eve_character_id',
            field=models.BigIntegerField(null=True, blank=True, db_index=True, help_text='EVE Online Character ID of first linked character (deprecated)'),
        ),

        # Step 2: Add new fields to Character model (nullable initially)
        migrations.AddField(
            model_name='character',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=255, help_text='EVE Online Character Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='corporation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='alliance_id',
            field=models.BigIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='alliance_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Encrypted OAuth2 refresh token for this character'),
        ),
        migrations.AddField(
            model_name='character',
            name='token_expires',
            field=models.DateTimeField(null=True, blank=True),
        ),

        # Step 3: Change Character.user from OneToOneField to ForeignKey
        # by removing the UNIQUE constraint on user_id
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey('core.User', on_delete=models.deletion.CASCADE, related_name='characters'),
        ),

        # Step 4: Populate User.username and Character fields from existing data
        migrations.RunPython(
            populate_usernames_and_character_fields,
            migrations.RunPython.noop,
        ),
    ]
