# Generated by Django 5.2.10 on 2026-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_character_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['character_name'], 'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='character',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(blank=True, default='', help_text='EVE Online Character Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='eve_character_name',
            field=models.CharField(blank=True, help_text='EVE Online Character Name of first linked character (deprecated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Deprecated: Use character.refresh_token instead'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated username for authentication', max_length=150, unique=True),
        ),
    ]
