# Generated by Django 5.2.10 on 2026-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_character_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited'), ('needs_reauth', 'Needs Re-authentication')], default='pending', max_length=20),
        ),
    ]
