# Generated by Django 5.2.10 on 2026-01-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_fitting_entry_offline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fittingcharge',
            new_name='core_fittin_fitting_078926_idx',
            old_name='core_fitting_fitting_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='fittingdrone',
            new_name='core_fittin_fitting_c71f44_idx',
            old_name='core_fittingdrone_fitting_bay_idx',
        ),
        migrations.AlterField(
            model_name='fittingcargoitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fittingcharge',
            name='fitting_entry',
            field=models.ForeignKey(blank=True, help_text='The module this charge is loaded into (optional, can be derived from position)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.fittingentry'),
        ),
        migrations.AlterField(
            model_name='fittingcharge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fittingcharge',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of charges (for cargo/bay storage)'),
        ),
        migrations.AlterField(
            model_name='fittingdrone',
            name='bay_type',
            field=models.CharField(choices=[('drone', 'Drone Bay'), ('fighter', 'Fighter Bay')], default='drone', help_text='Which bay this drone is in', max_length=10),
        ),
        migrations.AlterField(
            model_name='fittingdrone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fittingservice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='fittingservice',
            unique_together={('fitting', 'position')},
        ),
    ]
