# Generated by Django 5.2.10 on 2026-01-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_invalid_sync_status'),
        ('core', '0021_rename_core_fitting_fitting_entry_idx_core_fittin_fitting_078926_idx_and_more'),
    ]

    operations = [
    ]
