# Generated by Django 5.2.10 on 2026-01-22 15:16

from django.db import migrations


def noop(apps, schema_editor):
    """No-op migration - database was rebuilt from SDE with correct schema."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260122_1325'),
    ]

    operations = [
        # No-op migration
        # The database was rebuilt from SDE which already has all schema changes:
        # - Fields like highIsGood, stackable, unitID already exist with correct db_column
        # - Tables already renamed to core_* format
        # - All column mappings (db_column) already applied
        migrations.RunPython(noop, migrations.RunPython.noop),
    ]
