# Generated by Django 5.2.10 on 2026-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fitting_skill_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributetype',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='is_unique',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='station',
            name='is_conquerable',
        ),
        migrations.AddField(
            model_name='attributetype',
            name='high_is_good',
            field=models.BooleanField(db_column='highIsGood', default=True),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='stackable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='unit_id',
            field=models.IntegerField(blank=True, db_column='unitID', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='security',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='creator_corporation_id',
            field=models.IntegerField(blank=True, db_column='creatorCorporationID', null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='creator_id',
            field=models.IntegerField(blank=True, db_column='creatorID', null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='date_founded',
            field=models.DateField(blank=True, db_column='startDate', null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='id',
            field=models.BigIntegerField(db_column='allianceID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='default_value',
            field=models.FloatField(blank=True, db_column='defaultValue', null=True),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='display_name',
            field=models.CharField(blank=True, db_column='displayName', max_length=255),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='icon_id',
            field=models.IntegerField(blank=True, db_column='iconID', null=True),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='id',
            field=models.IntegerField(db_column='attributeID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='name',
            field=models.CharField(db_column='attributeName', max_length=255),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='faction_id',
            field=models.IntegerField(blank=True, db_column='factionID', null=True),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.BigIntegerField(db_column='corporationID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faction',
            name='corporation_id',
            field=models.IntegerField(blank=True, db_column='corporationID', null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='id',
            field=models.BigIntegerField(db_column='factionID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(db_column='factionName', max_length=255),
        ),
        migrations.AlterField(
            model_name='faction',
            name='solar_system_id',
            field=models.IntegerField(blank=True, db_column='solarSystemID', null=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='id',
            field=models.IntegerField(db_column='categoryID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(db_column='categoryName', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='category_id',
            field=models.IntegerField(db_column='categoryID', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='id',
            field=models.IntegerField(db_column='groupID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='name',
            field=models.CharField(db_column='groupName', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='group_id',
            field=models.IntegerField(db_column='groupID', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='id',
            field=models.BigIntegerField(db_column='typeID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(db_column='typeName', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='portion_size',
            field=models.IntegerField(blank=True, db_column='portionSize', null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigIntegerField(db_column='regionID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_column='regionName', max_length=255),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='constellation_id',
            field=models.IntegerField(blank=True, db_column='constellationID', null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='id',
            field=models.BigIntegerField(db_column='solarSystemID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='name',
            field=models.CharField(db_column='solarSystemName', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='region_id',
            field=models.IntegerField(db_column='regionID', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='security_class',
            field=models.CharField(blank=True, db_column='securityClass', max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='corporation_id',
            field=models.IntegerField(blank=True, db_column='corporationID', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigIntegerField(db_column='stationID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(db_column='stationName', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='region_id',
            field=models.IntegerField(blank=True, db_column='regionID', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='solar_system_id',
            field=models.IntegerField(db_column='solarSystemID', db_index=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='type_id',
            field=models.IntegerField(blank=True, db_column='stationTypeID', null=True),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='attribute_id',
            field=models.IntegerField(db_column='attributeID', db_index=True),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='type_id',
            field=models.IntegerField(db_column='typeID', db_index=True),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='value_float',
            field=models.FloatField(blank=True, db_column='valueFloat', null=True),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='value_int',
            field=models.IntegerField(blank=True, db_column='valueInt', null=True),
        ),
        migrations.AlterModelTable(
            name='alliance',
            table='core_alliance',
        ),
        migrations.AlterModelTable(
            name='corporation',
            table='core_corporation',
        ),
        migrations.AlterModelTable(
            name='faction',
            table='core_faction',
        ),
        migrations.AlterModelTable(
            name='itemtype',
            table='core_itemtype',
        ),
        migrations.AlterModelTable(
            name='region',
            table='core_region',
        ),
        migrations.AlterModelTable(
            name='solarsystem',
            table='core_solarsystem',
        ),
        migrations.AlterModelTable(
            name='station',
            table='core_station',
        ),
    ]
