# Generated by Django 5.2.10 on 2026-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_attributetype_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for account recovery and verification', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for email verification token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(blank=True, help_text='Token for email verification magic links', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the email address has been verified'),
        ),
    ]
