# Generated by Django 5.2.10 on 2026-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_email_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification magic links', max_length=255, null=True, unique=True),
        ),
    ]
