# Generated by Django 5.2.10 on 2026-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_fix_email_token_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.IntegerField(db_index=True, help_text='Corporation ID that owns the structure')),
                ('solar_system_id', models.IntegerField(db_index=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('position_z', models.FloatField(blank=True, null=True)),
                ('type_id', models.IntegerField(db_index=True, help_text='ItemType ID of the structure')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_sync_status', models.CharField(default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Player Structure',
                'verbose_name_plural': 'Player Structures',
                'db_table': 'core_structure',
                'ordering': ['name'],
            },
        ),
    ]
