# Generated by Django 5.2.10 on 2026-01-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='assets_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='station_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='system_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorderhistory',
            name='station_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorderhistory',
            name='system_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
