# Generated by Django 5.2.10 on 2026-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_character_assets_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillqueueitem',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillqueueitem',
            name='training_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
