# Generated by Django 5.2.10 on 2026-01-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_skillqueueitem_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='location_synced_at',
            field=models.DateTimeField(blank=True, help_text='When location was last synced', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='solar_system_id',
            field=models.IntegerField(blank=True, help_text='Current solar system ID', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='station_id',
            field=models.BigIntegerField(blank=True, help_text='Current station ID (if docked)', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='structure_id',
            field=models.BigIntegerField(blank=True, help_text='Current structure ID (if in structure)', null=True),
        ),
    ]
