# Generated by Django 5.2.10 on 2026-01-26 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_character_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitting',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this fitting (null = global/shared fitting)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_fittings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FittingIgnore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by', to='core.fitting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_fittings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fitting ignore',
                'verbose_name_plural': 'fitting ignores',
                'db_table': 'core_fittingignore',
                'indexes': [models.Index(fields=['user', 'fitting'], name='core_fittin_user_id_4ac79b_idx')],
                'unique_together': {('user', 'fitting')},
            },
        ),
    ]
