# Generated by Django 5.2.10 on 2026-01-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_fitting_ownership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillplanentry',
            unique_together={('skill_plan', 'skill_id', 'level')},
        ),
    ]
