# Generated by Django 5.2.10 on 2026-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_skillplanentry_level_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillplanentry',
            name='is_prerequisite',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this is an auto-added prerequisite skill, False if user-added goal'),
        ),
    ]
