# Generated by Django 5.2.10 on 2026-01-27 21:40

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_skillplanentry_is_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillplan',
            name='is_reference',
        ),
        migrations.AddField(
            model_name='skillplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='skillplan',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                help_text='User who owns this plan (null = global/shared plan)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='skill_plans',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
