# Generated by Django 5.2.10 on 2026-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_live_universe_browser'),
    ]

    operations = [
        # SovCampaign model fixes to match actual ESI response
        migrations.RemoveIndex(
            model_name='sovcampaign',
            name='eve_sov_cam_attacke_727f67_idx',
        ),
        migrations.RenameField(
            model_name='sovcampaign',
            old_name='attacker_score',
            new_name='attackers_score',
        ),
        migrations.RemoveField(
            model_name='sovcampaign',
            name='attacker_id',
        ),
        migrations.RemoveField(
            model_name='sovcampaign',
            name='attacker_name',
        ),
        migrations.RemoveField(
            model_name='sovcampaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='sovcampaign',
            name='defender_name',
        ),
        migrations.AddField(
            model_name='sovcampaign',
            name='event_type',
            field=models.TextField(blank=True, default='', help_text='ihub_defense, tcu_defense, etc.'),
        ),
        migrations.AddField(
            model_name='sovcampaign',
            name='structure_id',
            field=models.BigIntegerField(blank=True, help_text='The structure ID being contested', null=True),
        ),
        migrations.AlterField(
            model_name='activeincursion',
            name='type_id',
            field=models.IntegerField(blank=True, help_text='Incursion type (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='sovcampaign',
            name='defender_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sovcampaign',
            name='region_id',
            field=models.IntegerField(blank=True, help_text='Not provided by ESI, can be looked up', null=True),
        ),
        migrations.AlterField(
            model_name='sovcampaign',
            name='system_id',
            field=models.IntegerField(db_index=True, help_text='solar_system_id from ESI'),
        ),
        migrations.AddIndex(
            model_name='sovcampaign',
            index=models.Index(fields=['defender_id'], name='eve_sov_cam_defende_d9bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='sovcampaign',
            index=models.Index(fields=['event_type'], name='eve_sov_cam_event_t_6e946c_idx'),
        ),
    ]
