# Generated by Django 5.2.10 on 2026-01-28 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_fix_live_models_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPlanIgnore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'skill plan ignore',
                'verbose_name_plural': 'skill plan ignores',
                'db_table': 'core_skillplanignore',
            },
        ),
        migrations.AddField(
            model_name='loyaltystoreoffer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loyaltystoreoffer',
            name='offer_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='skillplanentry',
            unique_together={('skill_plan', 'skill_id', 'level')},
        ),
        migrations.AddConstraint(
            model_name='loyaltystoreoffer',
            constraint=models.UniqueConstraint(fields=('corporation', 'offer_id'), name='unique_corp_offer'),
        ),
        migrations.AddField(
            model_name='skillplanignore',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by', to='core.skillplan'),
        ),
        migrations.AddField(
            model_name='skillplanignore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_skill_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skillplanignore',
            unique_together={('user', 'plan')},
        ),
    ]
