# Generated by Django 5.2.10 on 2026-01-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fix_loyalty_offer_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltystoreoffer',
            name='ak_cost',
            field=models.BigIntegerField(default=0, help_text='Alternative currency cost (e.g., PLEX)'),
        ),
        migrations.AddField(
            model_name='loyaltystoreoffer',
            name='required_items',
            field=models.JSONField(default=list, help_text='Required items for exchange'),
        ),
    ]
