# Generated by Django 5.2.10 on 2026-01-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_lp_offer_required_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltystoreoffer',
            name='required_standing',
        ),
    ]
