# Generated by Django 5.2.10 on 2026-01-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_required_standing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FittingMatch',
        ),
    ]
