# Generated by Django 5.2.10 on 2026-01-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_fitting_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitting',
            old_name='is_tracked',
            new_name='is_pinned',
        ),
    ]
