# Generated by Django 5.2.10 on 2026-01-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_is_tracked_to_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitting',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this fitting is pinned to the top of the list'),
        ),
    ]
